CREATE TABLE IF NOT EXISTS tillage (
    name TEXT,
    additional_leaf_removed REAL,
    rate_4_modifier REAL,
    liters_per_hectare REAL
);
CREATE TABLE IF NOT EXISTS crops (
    id INTEGER PRIMARY KEY,
    name TEXT,
    plant_ratio REAL,
    root_distribution REAL,
    leaf_returned INTEGER,
    plant_moisture_factor REAL,
    harvest_index REAL,
    roots REAL,
    description TEXT,
    units_metric TEXT,
    units_imperial TEXT,
    default_yield REAL,
    default_n INTEGER,
    root_n REAL,
    biomass_n REAL
);
INSERT INTO tillage (
        name,
        additional_leaf_removed,
        rate_4_modifier,
        liters_per_hectare
    )
VALUES ('no-till', 1.0, 0.9, 26.0),
    ('reduced', 0.55, 0.975, 33.0),
    ('conventional', 0.35, 1.0, 47.0);
INSERT INTO crops (
        id,
        name,
        plant_ratio,
        root_distribution,
        leaf_returned,
        plant_moisture_factor,
        harvest_index,
        roots,
        "description",
        units_metric,
        units_imperial,
        default_yield,
        default_n,
        root_n,
        biomass_n
    )
VALUES (
        1,
        'wheat',
        0.59,
        0.33,
        1,
        0.155,
        0.39,
        0.4,
        'winter wheat',
        'MT/ha',
        'bu/ac',
        2.7,
        74,
        0.009,
        0.006
    ),
    (
        3,
        'corn',
        0.59,
        0.33,
        1,
        0.155,
        0.52,
        0.4,
        'Corn grain',
        'MT/ha',
        'bu/ac',
        9.3,
        159,
        0.007,
        0.006
    ),
    (
        6,
        'soybean',
        0.66,
        0.35,
        1,
        0.155,
        0.42,
        0.4,
        'Soybeans',
        'MT/ha',
        'bu/ac',
        2.6,
        0,
        0.008,
        0.008
    ),
    (
        2,
        'oats',
        0.59,
        0.33,
        1,
        0.155,
        0.5,
        0.4,
        'Oats',
        'MT/ha',
        'bu/ac',
        3.9,
        74,
        0.008,
        0.007
    ),
    (
        4,
        'switchgrass',
        0.59,
        0.33,
        0,
        0.155,
        1,
        0.5,
        'Switchgrass/Hay',
        'MT/ha',
        't/ac',
        7,
        NULL,
        0.012,
        0.15
    ),
    (
        5,
        'silage',
        0.59,
        0.33,
        0,
        0.155,
        1,
        0.4,
        'Corn silage',
        'MT/ha',
        't/ac',
        33,
        159,
        0.007,
        0.006
    ),
    (
        7,
        'alfalfa',
        0.6,
        0.35,
        0,
        0.155,
        1,
        0.4,
        'Alfalfa',
        'MT/ha',
        't/ac',
        6,
        NULL,
        0.019,
        0.027
    );